### ISSUE TITLE
Investigate generation of routable Maps.me exports

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool#261] opened 2017-10-04 20:51 UTC

**Comment by mojodna** [comment] 2017-10-09 14:54
@Locke has been looking into this with partial success.

**Comment by Locke** [comment] 2017-10-09 16:16
Hi,

I want to give you an update of my investigation so far. I can create mwm files locally with routing, but I'm still struggling with the docker integration.


Generating routing information requires to build the OSRM backend as well, with `CONFIG=gtool omim/tools/unix/build_omim.sh -cro`. This needs more build dependencies, therefore I replaced the base_image/Dockerfile "as omim" section with the content of https://github.com/mapsme/omim/blob/master/docs/debian/Dockerfile 

Calculating the routes needs libqt5network5 as runtime dependency (otherwise `generate_mwm.sh` from the celery worker container it fails with `/usr/local/bin/generator_tool: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory`), therefore I added it to the base_image.

You can see these changes in my development branch at https://github.com/hotosm/osm-export-tool/compare/master...Locke:feature-261 (Note: I tried to add a error-logger in mwm.py but it somehow doesn't work, output is "None"..)

Open tasks:

1.

In order to create the routing information a poly file of the exported area needs to be present (see https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format for a description of the format). I think it can be easily created from geosjon, but that's not a problem that I'm looking into now. Feel free to pick this up if you like.

- Note: Routing outside of the exported area into other areas will likely not work as all of the neighboring poly files need to be present, and the current poly file would have to have been present at their routing calculation. This is related to the necessity of renaming the exported mwm file to the expected filename from the app (but not caused by it, it's just that the app isn't designed for varying shapes).

2.

The generation behaves different in the container than locally. I suspect some more files are missing that need to be copied over from the omim container. This is the part I'm focusing on.

When I try to run the tool it tries to create files in the root (for example "generator/search_index_builder.cpp:460 BuildSearchIndexFromDataFile() Error writing index file: /babenhausen_export.sdx.tmp; Write truncate; Permission denied") which of course fails for the exports user. I also saw that the tool tried to delete the "/root" folder...

Therefore I use a intermittent docker cache file from before the "USER exports" statement in an interactive session. 

When I add a valid .poly file for the BORDERS_PATH variable* the generation looks like it works (esp. the last two lines "LOG TID(1) INFO       2.2146 generator/routing_index_generator.cpp:326 FillWeights() Leaps finished, elapsed: 2.19611 seconds, routes found: 9027 , not found: 382
LOG TID(1) INFO      2.21575 generator/routing_index_generator.cpp:401 BuildCrossMwmSection() Cross mwm section generated, size: 15462 bytes" are present in both the container and with my local setup) - but the generated mwm still crashes the app when I try to create a route :(

* There is a known bug in the generator_tool, therefore I'm using BORDERS_PATH instead of POLY, see https://github.com/mapsme/omim/pull/7215

**Comment by bdon** [comment] 2017-10-09 18:07
> In order to create the routing information a poly file of the exported area needs to be present

We have an implementation of this here:
https://github.com/hotosm/osm-export-tool/blob/master/utils/garmin_img.py#L11

**Comment by Locke** [comment] 2017-10-11 22:33
Thanks for the implementation, I copied it over.

> The generation behaves different in the container than locally

Turns out the introduction of MWM_WRITABLE_DIR depends on the presence of `eula.html`. The commit 338f6deea might be (manually) cherry-picked onto master as it's independent of the routing feature (and it appears mwm generation is broken since the last baseimage update).

> the generation looks like it works (esp. the last two lines "LOG TID(1) INFO 2.2146 generator/routing_index_generator.cpp:326 FillWeights() Leaps finished, elapsed: 2.19611 seconds, routes found: 9027 , not found: 382
LOG TID(1) INFO 2.21575 generator/routing_index_generator.cpp:401 BuildCrossMwmSection() Cross mwm section generated, size: 15462 bytes" are present in both the container and with my local setup) - but the generated mwm still crashes the app when I try to create a route :(

This is the only thing left.

**Comment by Locke** [comment] 2017-10-28 23:12
> but the generated mwm still crashes the app when I try to create a route :(

Apparently the generation tool is not backwards compatible. As per my comment in slack/gitter the master and release-76 branch of omim crashes the 7.5 android app, but the release-75 branch doesn't.

Now I've tested the recently released 7.6 app with both the release-75 and release-76 branch and encountered no crashes. Surprisingly cross-mwm routing worked although the folder for the BORDER_PATH doesn't contain any surrounding poly files.

I have created a PR at https://github.com/hotosm/osm-export-tool/pull/272

The BRANCH variable should be updated manually from time to time.

**Comment by bdon** [comment] 2019-07-20 22:11
The Maps.ME generator tooling seems to have diverged significantly since this work was done, so I don't think this routing feature can be merged anymore. Let me know if there is still a need for this however and I can look into moving to the new toolset.

**Closed by bdon** 2019-07-20 22:11 UTC
Labels: Type: Enhancement
