### ISSUE TITLE
Milestone 4. Collected stats from production

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#321] opened 2019-07-10 19:50 UTC
@bdon Collected aggregate stats on existing export tool usage from production DB

![Screen Shot 2019-07-10 at 12 48 34](https://user-images.githubusercontent.com/8972913/60999895-1692c600-a311-11e9-95c5-dbe2d40997fe.png)

![Screen Shot 2019-07-10 at 12 48 44](https://user-images.githubusercontent.com/8972913/60999905-1c88a700-a311-11e9-911f-589782e79481.png)

note. user stats are new users registering not the total number of users actively creating exports

**Comment by bdon** [comment] 2019-10-19 15:34
duplicate of #273

**Closed** 2019-10-19 15:34 UTC
Labels: Component: Backend
