### ISSUE TITLE
Clone - step 3 data - Configs tab disappears

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool#278] opened 2017-11-17 16:00 UTC
When cloning a project and using the 'next' buttons, I get to step 3 and if I click on the tag tree tab or configs tab, the configs tab disappears.

![2017-11-17_16h54_29](https://user-images.githubusercontent.com/265831/32956331-c5275668-cbb8-11e7-87e8-d178b5b3dd45.png)

After clicking on the "configs" tab:

![2017-11-17_16h54_52](https://user-images.githubusercontent.com/265831/32956338-c9c41d64-cbb8-11e7-85ee-046c89c703f5.png)

**Comment by mataharimhairi** [comment] 2018-01-23 08:11
@bgirardot Is this just with exporting .obf files? I've been using stored configs to generate .gpkg files with no issue.

**Comment by bdon** [comment] 2018-01-23 16:32
This is a duplicate of #282

**Comment by bdon** [comment] 2019-07-26 02:11
There was a check here that would hide the "configs" tab if 0 configs were visible to the user. This is always shown now.

**Closed by bdon** 2019-07-26 02:11 UTC
Labels: Type: Bug
