### ISSUE TITLE
Linking Export Tool with fieldcampaigner - Feature Request

### ISSUE THREAD

**Issue by Dragneel7** [hotosm/osm-export-tool#296] opened 2018-08-06 10:06 UTC
To enhance the usability of fieldcampaigner(http://campaigns.hotosm.org), we are planning to add a new feature of export campaign in the campaign details page.
This new feature will create a link between the field campaigner and export tool and the geoJSON data can be exported in the user desired formats.
To do this, it would be reasonable if there exists an api endpoint which fieldcampainger views can call.
@mojodna @cchristelis Does an api point already exists? or Is the above approach feasible?
Thanks.

**Comment by bdon** [comment] 2019-07-26 22:40
This need sounds like it could be met by #304 , but i'm not totally familiar with FieldCampaigner. @mataharimhairi

**Comment by mataharimhairi** [comment] 2019-07-30 23:52
@bdon The permalinks (#304 ) would allow for a non-expiring link, but building out interoperability between MapCampaigner and the Export Tool would take much more work. Let's talk to @smit1678  about this, and what the dev plans for MapCampaigner in the near future are.

**Comment by bdon** [comment] 2019-10-19 16:43
Duplicate of #304

**Closed by bdon** 2019-10-19 16:43 UTC
Labels: Component: Backend, Difficulty: Hard, Type: Enhancement
